server:
  port: 9010

spring:
  application:
    name: API-GATEWAY
  profiles: op

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://iqsbz-new-op.ap-northeast-2.elasticbeanstalk.com/eureka/}
zuul:
  routes:
    okr-service:
      path: /okr/**
      service-id: OKR-SERVICE
    ps-service:
      path: /ps/**
      service-id: PS-SERVICE
    rs-service:
      path: /rs/**
      service-id: RS-SERVICE
    cm-service:
       path: /cm/**
       service-id: CM-SERVICE
