spring:
  profiles: op
  message: Hello Spring DO - SERVICE dev Server!!
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


ps-service:
  datasource:
    jdbc-url: jdbc:mysql://iqsbz-operation.cmzny3nijw9z.ap-northeast-2.rds.amazonaws.com:3306/ps_service?serverTimezone=UTC
    username: iqsbz
    password: '!SqiSoft00'
    maximum-pool-size: 3
    connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver

iqsbz3:
  datasource:
    jdbc-url: jdbc:mysql://iqsbz-operation.cmzny3nijw9z.ap-northeast-2.rds.amazonaws.com:3306/iqsbz3?serverTimezone=UTC
    username: iqsbz
    password: '!SqiSoft00'
    maximum-pool-size: 3
    connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    idle-timeout: 100000
    validation-timeout: 3000
    max-lifetime: 180000

do-service:
  datasource:
    jdbc-url: jdbc:mysql://iqsbz-operation.cmzny3nijw9z.ap-northeast-2.rds.amazonaws.com:3306/do_service?serverTimezone=UTC
    username: iqsbz
    password: '!SqiSoft00'
    maximum-pool-size: 1
    connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver

redmine-aws:
  datasource:
    jdbc-url: jdbc:mariadb://13.125.46.12:3306/redmine?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 'redmine'
    maximun-pool-size: 2
    connection-test-query: SELECT 1
    driver-class-name: org.mariadb.jdbc.Driver

pm-service:
  datasource:
    jdbc-url: jdbc:mysql://iqsbz-operation.cmzny3nijw9z.ap-northeast-2.rds.amazonaws.com:3306/pm_service?serverTimezone=UTC&allowMultiQueries=true
    username: iqsbz
    password: '!SqiSoft00'
    maximum-pool-size: 3
    connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver

fi-service:
  datasource:
    jdbc-url: jdbc:mysql://iqsbz-operation.cmzny3nijw9z.ap-northeast-2.rds.amazonaws.com:3306/fi_service?serverTimezone=UTC&allowMultiQueries=true
    username: iqsbz
    password: '!SqiSoft00'
    maximum-pool-size: 3
    connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver

sm-service:
  datasource:
    jdbc-url: jdbc:mysql://iqsbz-test.cmzny3nijw9z.ap-northeast-2.rds.amazonaws.com:3306/sm_service?serverTimezone=UTC
    username: iqsbz
    password: '!Sqisoft00'
    maximum-pool-size: 2
    connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
