spring:
  profiles: dev
  message: Hello Spring FI - SERVICE dev Server!!
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


fi-service:
  datasource:
    jdbc-url: jdbc:mysql://iqsbz-test.cmzny3nijw9z.ap-northeast-2.rds.amazonaws.com:3306/fi_service?serverTimezone=UTC&allowMultiQueries=true
    username: iqsbz
    password: '!SqiSoft00'
    maximum-pool-size: 1
    connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver


iqsbz3:
  datasource:
    jdbc-url: jdbc:mysql://iqsbz-test.cmzny3nijw9z.ap-northeast-2.rds.amazonaws.com:3306/iqsbz3?serverTimezone=UTC
    username: iqsbz
    password: '!SqiSoft00'
    maximum-pool-size: 1
    connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    idle-timeout: 100000
    validation-timeout: 3000
    max-lifetime: 180000
