spring:
  profiles: dev
  message: Hello Spring PS - SERVICE dev Server!!
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://iqsbz-test.cmzny3nijw9z.ap-northeast-2.rds.amazonaws.com:3306/iqsbz5?serverTimezone=UTC
      username: iqsbz
      password: '!SqiSoft00'
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
     
