spring:
  profiles: local
  message: Hello Spring PS - SERVICE Local Server!!
  datasource:
    username: iqsbz
    password: '!Sqisoft00'
    maximum-pool-size: 3
    connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.203:3306/ps_service?serverTimezone=UTC
    idle-timeout: 100000
    validation-timeout: 3000
    max-lifetime: 180000
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect     
