spring:
  profiles: local
  message: Hello Spring RS - SERVICE Local Server!!
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    rs-service:
      username: iqsbz
      password: '!Sqisoft00'
      maximum-pool-size: 3
      connection-test-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.3.203:3306/ps-service?serverTimezone=UTC
      idle-timeout: 100000
      validation-timeout: 3000
      max-lifetime: 180000
      
    iqsbz3:
      username: iqsbz
      password: '!Sqisoft00'
      maximum-pool-size: 3
      connection-test-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.3.203:3306/iqsbz3?serverTimezone=UTC
      idle-timeout: 100000
      validation-timeout: 3000
      max-lifetime: 180000
